# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: blog
email: ferjmoreno@gmail.com
description: coding out loud
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ferjm.github.io" # the base hostname & protocol for your site
twitter_username: f_jimenez
github_username:  ferjm
paginate: 5
theme-dark: true #Set to true to change to dark website theme
google_analytics: UA-76885315-1

plugins: [jekyll-paginate, kramdown, jekyll-seo-tag]
# Build settings
markdown: kramdown
